version: "3.4"

networks:
  orleans-demo-network:
    driver: bridge

services:

  demo-service:
    build:
      context: .
      dockerfile: demo/Dockerfile
    ports:
    - "5000:80"
    networks:
    - orleans-demo-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./demo/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: always
    networks:
      - orleans-demo-network
