global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: demo-service
    static_configs:
      - targets:
        - demo-service:80
  - job_name: demo-service-replica
    static_configs:
      - targets:
        - demo-service-replica:80
